export const GET_PARTER_LIST_ERROR_MESSAGE = 'Невозможно получить список партнеров';
export const GET_CLIENT_LIST_ERROR_MESSAGE = 'Невозможно получить список Клиентов';
export const GET_BANK_INFO_ERROR_MESSAGE = 'Невозможно получить информацию о банке';
export const BANK_NOT_DEFINED_CONTROL_MESSAGE = 'Банк не определен. Проверьте БИК';
export const SET_INN_CONTROL_MESSAGE = 'Укажите ИНН контрагента';
export const SET_INN_VALID_LENGTH_CONTROL_MESSAGE = 'Укажите ИНН 10 или 12 цифр';
export const SET_RECEIVER_BIK_CONTROL_MESSAGE = 'Укажите БИК банка получателя';
export const SET_RECEIVER_ACCOUNT_CONTROL_MESSAGE = 'Укажите счет получателя';
export const INVALID_RECIVER_ACCOUNT_CONTROL_MESSAGE = 'Некорректный счёт получателя';
