import { NgModule } from '@angular/core';

import {
  BaseModalModule,
  ButtonModule,
  CheckboxModule,
  DatepickerModule,
  DropdownModule,
  FormFieldModule,
  HeadingModule,
  IconModule,
  InputAutocompleteModule,
  InputSelectModule,
  NumberInputModule,
  PhoneInputModule,
  SpinnerIconModule,
  TemplateTypeModule,
  TextInputModule,
  TextModule,
  TooltipModule,
} from '@psb/fe-ui-kit';

@NgModule({
  imports: [
    TooltipModule,
    CheckboxModule,
    ButtonModule,
    TextInputModule,
    TextModule,
    HeadingModule,
    NumberInputModule,
    IconModule,
    FormFieldModule,
    SpinnerIconModule,
    InputSelectModule,
    DropdownModule,
    InputAutocompleteModule,
    TemplateTypeModule,
    DatepickerModule,
    BaseModalModule,
    PhoneInputModule,
  ],
  exports: [
    TooltipModule,
    CheckboxModule,
    ButtonModule,
    TextInputModule,
    TextModule,
    HeadingModule,
    NumberInputModule,
    IconModule,
    FormFieldModule,
    SpinnerIconModule,
    InputSelectModule,
    DropdownModule,
    InputAutocompleteModule,
    TemplateTypeModule,
    DatepickerModule,
    BaseModalModule,
    PhoneInputModule,
  ],
})
export class PsbModule {}
