import { NgModule } from '@angular/core';

import { FormatMoneyPipe, SecurePipe } from './pipes';

import {
    BannerModule,
    BaseModalModule,
    ButtonModule,
    CheckboxModule,
    DatepickerModule,
    DropdownModule,
    FormFieldModule,
    HeadingModule,
    IconModule,
    InputAutocompleteModule,
    InputSelectModule,
    NotificationModule,
    NumberInputModule,
    PhoneInputModule,
    ScrollBarModule,
    SpinnerIconModule,
    TemplateTypeModule,
    TextInputModule,
    TextModule,
    TooltipModule,
} from '@psb/fe-ui-kit';

@NgModule({
    declarations: [
        FormatMoneyPipe,
        SecurePipe,
    ],
    imports: [
        TooltipModule,
        CheckboxModule,
        ButtonModule,
        BannerModule,
        ScrollBarModule,
        TextInputModule,
        TextModule,
        HeadingModule,
        NumberInputModule,
        IconModule,
        FormFieldModule,
        SpinnerIconModule,
        InputSelectModule,
        DropdownModule,
        InputAutocompleteModule,
        TemplateTypeModule,
        DatepickerModule,
        BaseModalModule,
        PhoneInputModule,
        NotificationModule,
    ],
    exports: [
        TooltipModule,
        CheckboxModule,
        ButtonModule,
        BannerModule,
        ScrollBarModule,
        TextInputModule,
        TextModule,
        HeadingModule,
        NumberInputModule,
        IconModule,
        FormFieldModule,
        SpinnerIconModule,
        InputSelectModule,
        DropdownModule,
        InputAutocompleteModule,
        TemplateTypeModule,
        DatepickerModule,
        BaseModalModule,
        PhoneInputModule,
        NotificationModule,
        FormatMoneyPipe,
        SecurePipe,
    ],
})
export class PsbModule { }
